import React from 'react';
import { Card, Button, Container, Row, Col } from 'react-bootstrap';
import '../../../css/EchoInstructions.css'

const exampleData = [
  {
    name: 'Basic',
    description: 'This is the basic example, with two control dilution patterns, two control single point patterns, and two treatment dilution patterns. Two columns on each plate are empty as DMSO controls.',
    filename: 'RippleTemplate_Basic.xlsx'
  },
  {
    name: 'Multi-Source Concentration',
    description: 'Uses multiple source concentrations to avoid intermediate plates. DMSO wells are included on the source plate for normalization.',
    filename: 'RippleTemplate_MultiSrcConc.xlsx'
  },
  {
    name: 'Interleaved Patterns',
    description: 'Destination plate patterns are interleaved, demonstrating concatenated well block notation.',
    filename: 'RippleTemplate_Interleaved.xlsx'
  },
  {
    name: 'Warning Example',
    description: 'Illustrates what happens when a solution cannot be calculated. The precalculator will display a warning, and if the user proceeds, the problematic wells will not have compound transfered to them.',
    filename: 'RippleTemplate_ConcentrationWarning.xlsx'
  },
  {
    name: 'Combinations',
    description: 'Shows the Combination pattern type, which will test each member compound against each other compound in the pattern in perpendicular curves. Also has DMSO solvent wells to avoid intermediate plate creation.',
    filename: 'RippleTemplate_Combination.xlsx'
  }
];

const About: React.FC = () => {
  return (
    <div className="echo-instructions-wrapper">
      <Container fluid className="d-flex flex-column gap-3">
        <Row className="g-3">
          <Col md={6} className="d-flex echo-instructions">
            <Card className="shadow-sm flex-fill">
              <Card.Body>
                <Card.Title as="h4" className="mb-4 text-center">About</Card.Title>
                <p>
                  This tool is intended to supplement use of the official Echo Dose Response software, allowing rapid changes to established protocols, such as different numbers of test compounds or plate layouts.
                  It takes user-provided assay constraints and attempts to calculate a viable transfer scheme using up to two levels of intermediate plates. It tracks combined required volumes, moving between wells once they are depleted.
                  Intermediate plates are assumed to be completely filled with a set DMSO volume, and wells without intermediate compound are then used for DMSO normalization. The final transfer list is sorted by source plate to intermediate plate,
                  then intermediate to intermediate, source to destination, and finally intermediate to destination.
                </p>
                <p>
                  Due to the fundamental constraint of 2.5nL droplets, the tool uses a series of heuristics to find a viable transfer scheme. However, it is not guaranteed to be the most efficient, nor to always find one successfully, and will alert the user in such a case.
                </p>
              </Card.Body>
            </Card>
          </Col>
          <Col md={6} className="d-flex echo-instructions">
            <Card className="shadow-sm flex-fill">
              <Card.Body>
                <Card.Title as="h4" className="mb-4 text-center">Template Structure</Card.Title>
                <ul className="template-card">
                  <li><strong>Patterns:</strong> One row per pattern, with type, direction, replicates, and the concentration series (<code>Conc1</code>…<code>Conc20</code>).</li>
                  <li><strong>Layout:</strong> Each pattern's well block(s) on the destination plate. A colon (<code>:</code>) separates the start and end of a rectangle; a semicolon (<code>;</code>) separates disjoint rectangles, <i>e.g.,</i> <code>A01:P01;A24:P24</code> for the two outer columns.</li>
                  <li><strong>Compounds:</strong> Source barcode, well ID(s), stock concentration (µM), compound ID, well volume (µL), and linked pattern. Multiple patterns can be assigned by separating with a semicolon, <i>e.g.,</i> <code>Treatment;MaxCtrl</code></li>
                  <li><strong>Barcodes:</strong> Optional intermediate and destination plate barcodes, used in order. Missing barcodes are autogenerated.</li>
                  <li><strong>Assay:</strong> Optional assay parameters (DMSO tolerance, well volume, etc.) that pre-fill the Calculator form on upload. Binary settings use 1 (true) or 0 (false).</li>
                </ul>
              </Card.Body>
            </Card>
          </Col>
        </Row>
        <Row>
          <Col className='echo-instructions'>
            <Card className="shadow-sm">
              <Card.Body className="p-0">
                <Card.Title as="h4" className="my-4 text-center">Examples</Card.Title>
                <div className="example-grid">
                  {exampleData.map((example, index) => (
                    <div key={index} >
                      <div className="example-content">
                        <div className="example-header">
                          <h5>{example.name}</h5>
                          <Button
                            variant="outline-primary"
                            href={`/ripple/data/${example.filename}`}
                          >
                            Download
                          </Button>
                        </div>
                        <p>{example.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default About;